---
title: "Integration"
subtitle: "`r knitr::current_input(dir = TRUE)`"
author: "Mark Jones"
date: "`r Sys.time()`"
output:
  html_document:
    number_sections: yes
    self_contained: yes
    theme: united
    toc: yes
    toc_depth: 3
geometry: left=0.2cm,right=0.2cm,top=1cm,bottom=1cm
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
# setwd("~/Documents/examples/015_math")
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages(library(rstan))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(nphsim))
suppressPackageStartupMessages(library(survival))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(brms))
```

# Integration by parts

Consider that we want to solve the integral $\int x^2 ln(x) dx$. 

Let $u$ and $v$ be functions of x. The product rule is $\frac{d}{dx}(uv) = u \frac{dv}{dx} + v \frac{du}{dx}$. Integrate the product rule to get $uv = \int u \frac{dv}{dx} dx + \int v \frac{du}{dx} dx$. Rearranging gives the structure for integration by parts.

\begin{aligned}
\int u \frac{dv}{dx} dx = uv - \int v \frac{du}{dx} dx
\end{aligned}

Return to the integral we want to solve. There is an $log$ in the product so you have to set $u = log(x)$ (because you don't have an integral for log(x) and then set $dv = x^2 dx$.

If $u = log(x)$ then $\frac{du}{dx} = \frac{1}{x}$.

If $\frac{dv}{dx} = x^2$ then $v = \int x^2 dx = \frac{x^3}{3} + c$ (but ignore the c for now). Substitution shows we now have the desired form:

\begin{aligned}
  \int log(x) x^2 dx &= \int u \frac{dv}{dx}dx \\
\end{aligned}

Solving:

\begin{aligned}
  \int log(x) x^2 dx &= \frac{x^3}{3}log(x) - \int \frac{x^3}{3}\frac{1}{x}dx \\
  &= \frac{x^3}{3}log(x) - \int \frac{x^2}{3}dx \\ 
  &= \frac{x^3}{3}log(x) - \frac{x^3}{9} + c \\ 
  &= \frac{x^3}{3}(log(x) - 1/3) + c
\end{aligned}

> RULES: (1) if one of the factors is a log function - set that log function to u (2) if there is no log term, the power of x is taken as u (3) if there is no log nor power of x then the exponential is u.

> NOTE: You may need to go through the process multiple times and you may need to do an $I$ substitution if you end up where you started.


# Integrals of form $\int \frac{f'(x)}{f(x)}dx$ or $\int f'(x)f(x)dx$

Consider $\int \frac{2x + 3}{x^2 + 3x -5} dx$. Notice that if we set the denominator $z=x^2 + 3x -5$ then $\frac{dx}{dz} = 2x + 3$. 

We can pretend $dx =(2x + 3) dz$. Substitution gives

\begin{aligned}
  \int \frac{2x + 3}{x^2 + 3x -5} dx  &= \int \frac{1}{z} dz \\
  &= log(z) + c
\end{aligned}

Substitute again: $\int \frac{2x + 3}{x^2 + 3x -5} dx = log(x^2 + 3x -5) + c$.

> Any integral of the form $\int \frac{f'(x)}{f(x)}dx$ has the solution $log(f(x)) + c$.


Similarly consider $\int (x^2+7x-4)(2x+7) dx$. Notice that if $z = x^2+7x-4$, $\frac{dz}{dx} = 2x + 7$. Substitution gives $\int (x^2+7x-4)(2x+7) dx = \int z dz = \frac{z^2}{2}+c$.

Substitute again: $\int (x^2+7x-4)(2x+7) dx = \frac{(x^2+7x-4)^2}{2}+c$.


\  
\  
\   
\    
. 








